### ISSUE TITLE
Compilation error in 32 bit build

### ISSUE THREAD

**Issue by thijsc** [badboy/crc64-rs#3]
I ran into this error when making a 32 bit build:

```
src/lib.rs:112:52: 112:66 error: transmute called on types with different sizes: &[u8] (64 bits) to (*const u64, u64) (96 bits)
src/lib.rs:112                 let (tmp, _) : (*const u64, u64) = mem::transmute(&$curVec);
```

Not exactly sure how to fix this, glad to take a look at it though. Do you have any pointers?

**Comment by badboy** [comment]
Can you try replacing the second `u64` with `usize` and report back?

**Comment by thijsc** [comment]
Thanks! :-)

**Comment by badboy** [comment]
Thanks for the report. I had some free time and just spin up a virtual machine.
